[general]
log_level = "info"

# Where you want the proxy to listen for incoming connections
[server]
listen_host = "0.0.0.0"
listen_port = 8080

# The URL we are sending requests to and rewriting
[upstream]
url = "http://localhost:8000"

# For example here
# <alie>This is a lie, and what AI bots will see!</alie>
# <atrue>This is the truth, and what users will see!</atrue>
[rewrite_tag]
lie_tag_name = "alie"
true_tag_name = "atrue"

[image]
# In the "content" replace_method, we don't rewrite the tags but instead
# just serve a random other different image in response to image requests
# Not yet implemented
# replace_method = "content"
# In the "tag" replace_method, we swap out the src attribute for some other
# random image
replace_method = "tag"
replace_source = "assets/replacement-images/"

# Just a list to get started
# Note that if you lie to things like Googlebot and Facebookbot it will
# affect search results and link previews and that sort of thing. But maybe
# that's a good thing?
[bots.google]
user_agent_contains = ["Googlebot", "Bard-Google", "Google-Extended"]

[bots.openai]
user_agent_contains = ["GPTBot", "OAI-SearchBot", "ChatGPT-User"]

[bots.apple]
user_agent_contains = ["Applebot"]
enabled = false # Siri AI is terrible who cares

[bots.anthropic]
user_agent_contains = ["Claude-Web", "Anthropic-ai", "ClaudeBot"]

[bots.bytedance]
user_agent_contains = ["Bytespider"]

[bots.perplexity]
user_agent_contains = ["PerplexityBot"]

[bots.facebook]
user_agent_contains = ["Facebookbot", "Meta-ExternalAgent", "Meta-ExternalFetcher"]

[bots.imagesiftbot]
user_agent_contains = ["Imagesiftbot"]
